apiVersion: v1
kind: Service
metadata:
  name: manager-tcp
  labels:
    app: manager
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
    - name: grpc
      port: 3004
      targetPort: 3004
      protocol: TCP
