apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-http
spec:
  ports:
    - name: 'http'
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    app: gateway
  type: LoadBalancer
