// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.2
//   protoc               v5.29.3
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "auth";

/** ---------- ENUMS ---------- */
export enum UserStatus {
  USER_STATUS_INACTIVE = 0,
  USER_STATUS_ACTIVE = 1,
  USER_STATUS_BLOCKED = 2,
  UNRECOGNIZED = -1,
}

export enum VerificationCodeType {
  REGISTER = 0,
  FORGOT_PASSWORD = 1,
  DISABLE_2FA = 2,
  LOGIN = 3,
  UNRECOGNIZED = -1,
}

export enum CompanyType {
  COMPANY_TYPE_UNKNOWN = 0,
  COMPANY_TYPE_SOLE_PROPRIETORSHIP = 1,
  COMPANY_TYPE_LLC = 2,
  COMPANY_TYPE_CORPORATION = 3,
  UNRECOGNIZED = -1,
}

export enum VerificationStatus {
  VERIFICATION_STATUS_PENDING = 0,
  VERIFICATION_STATUS_APPROVED = 1,
  VERIFICATION_STATUS_REJECTED = 2,
  UNRECOGNIZED = -1,
}

/** ---------- SHARED STRUCTS ---------- */
export interface Role {
  id: number;
  name: string;
}

export interface Permission {
  id: number;
  name: string;
  module: string;
  path: string;
  method: string;
}

export interface User {
  id: number;
  email: string;
  phone: string;
  password: string;
  name: string;
  avatar?: string | undefined;
  status: UserStatus;
  totpSecret?: string | undefined;
  roles: Role[];
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
  deletedAt?: Timestamp | undefined;
  createdById?: number | undefined;
  deletedById?: number | undefined;
  updatedById?: number | undefined;
}

export interface GetUserProfileResponse {
  user: User | undefined;
  role: Role | undefined;
  permissions: Permission[];
}

export interface ServiceProvider {
  id: number;
  userId: number;
  taxId: string;
  companyType: CompanyType;
  licenseNo?: string | undefined;
  industry?: string | undefined;
  description?: string | undefined;
  address: string;
  logo?: string | undefined;
  verificationStatus: VerificationStatus;
  verifiedAt?: Timestamp | undefined;
  verifiedById?: number | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

/** ---------- REQUESTS ---------- */
export interface RegisterRequest {
  name: string;
  email: string;
  phone: string;
  password: string;
  confirmPassword: string;
  code: string;
}

export interface RegisterProviderRequest {
  name: string;
  email: string;
  phone: string;
  password: string;
  confirmPassword: string;
  code: string;
  taxId: string;
  companyType: CompanyType;
  industry?: string | undefined;
  address: string;
  description?: string | undefined;
}

export interface LoginRequest {
  email: string;
  password: string;
  totpCode?: string | undefined;
  code?: string | undefined;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface LogoutRequest {
  refreshToken: string;
}

export interface ForgotPasswordRequest {
  email: string;
  code: string;
  newPassword: string;
  confirmNewPassword: string;
}

export interface SendOTPRequest {
  email: string;
  type: VerificationCodeType;
}

export interface GoogleAuthStateRequest {
  userAgent: string;
  ip: string;
}

export interface DisableTwoFactorRequest {
  totpCode?: string | undefined;
  code?: string | undefined;
}

/** ---------- RESPONSES ---------- */
export interface RegisterResponse {
  user: User | undefined;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
}

export interface GetAuthorizationUrlResponse {
  url: string;
}

export interface TwoFactorSetupResponse {
  secret: string;
  uri: string;
}

export interface MessageResponse {
  message: string;
}

export const AUTH_PACKAGE_NAME = "auth";

/** ---------- SERVICES ---------- */

export interface AuthServiceClient {
  register(request: RegisterRequest): Observable<RegisterResponse>;

  registerProvider(request: RegisterProviderRequest): Observable<MessageResponse>;

  login(request: LoginRequest): Observable<LoginResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<RefreshTokenResponse>;

  logout(request: LogoutRequest): Observable<MessageResponse>;

  sendOtp(request: SendOTPRequest): Observable<MessageResponse>;

  forgotPassword(request: ForgotPasswordRequest): Observable<MessageResponse>;

  getGoogleLink(request: GoogleAuthStateRequest): Observable<GetAuthorizationUrlResponse>;

  disableTwoFactor(request: DisableTwoFactorRequest): Observable<MessageResponse>;

  twoFactorSetup(request: GoogleAuthStateRequest): Observable<TwoFactorSetupResponse>;
}

/** ---------- SERVICES ---------- */

export interface AuthServiceController {
  register(request: RegisterRequest): Promise<RegisterResponse> | Observable<RegisterResponse> | RegisterResponse;

  registerProvider(
    request: RegisterProviderRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  refreshToken(
    request: RefreshTokenRequest,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;

  logout(request: LogoutRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  sendOtp(request: SendOTPRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  forgotPassword(
    request: ForgotPasswordRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getGoogleLink(
    request: GoogleAuthStateRequest,
  ): Promise<GetAuthorizationUrlResponse> | Observable<GetAuthorizationUrlResponse> | GetAuthorizationUrlResponse;

  disableTwoFactor(
    request: DisableTwoFactorRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  twoFactorSetup(
    request: GoogleAuthStateRequest,
  ): Promise<TwoFactorSetupResponse> | Observable<TwoFactorSetupResponse> | TwoFactorSetupResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "registerProvider",
      "login",
      "refreshToken",
      "logout",
      "sendOtp",
      "forgotPassword",
      "getGoogleLink",
      "disableTwoFactor",
      "twoFactorSetup",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
