// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.2
//   protoc               v5.29.3
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface AccessTokenRequest {
  accessToken: string;
}

export interface RoleMessage {
  id: number;
  name: string;
}

export interface AccessTokenPayload {
  userId: number;
  deviceId: number;
  providerId: number;
  staffProviderId: number;
  roles: RoleMessage[];
  exp: number;
  iat: number;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  authenticate(request: AccessTokenRequest): Observable<AccessTokenPayload>;
}

export interface AuthServiceController {
  authenticate(
    request: AccessTokenRequest,
  ): Promise<AccessTokenPayload> | Observable<AccessTokenPayload> | AccessTokenPayload;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
