// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.2
//   protoc               v5.29.3
// source: proto/manager.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "managers";

export interface ChangeStatusRequest {
  providerId: number;
  verificationStatus: string;
  managerId: number;
}

export interface MessageResponse {
  message: string;
}

export const MANAGERS_PACKAGE_NAME = "managers";

export interface ManagersServiceClient {
  changeProviderStatus(request: ChangeStatusRequest): Observable<MessageResponse>;
}

export interface ManagersServiceController {
  changeProviderStatus(
    request: ChangeStatusRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;
}

export function ManagersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["changeProviderStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ManagersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ManagersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MANAGERS_SERVICE_NAME = "ManagersService";
