apiVersion: v1
kind: Service
metadata:
  name: auth-tcp
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: grpc
      port: 3002
      targetPort: 3002
      protocol: TCP
